### ISSUE TITLE
Why use `nn.AvgPool2d` to get downsampled images?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [Blade6570/Photographic-Image-Synthesis-with-Cascaded-Refinement-Networks--Pytorch-#3]
It seems inconsistent with the official implementation.
```python
downsampled=tf.image.resize_area(label,(sp//2,sp),align_corners=False)
```

**Comment by Blade6570** [comment]
The exact implementation of tensorflow version for downsampling is not present in pytorch. I chose this to do the same in a computationally efficient form.
