### ISSUE TITLE
pretrained VGG19 and CRN weights are no longer able to download

### ISSUE THREAD

**Issue by ConvMech** [Blade6570/Photographic-Image-Synthesis-with-Cascaded-Refinement-Networks--Pytorch-#4]
Hello, I am trying to reproduce your work with the readme instruction. I found I currently do not have access to you pretrained models in google drive, could you release it?

**Comment by Blade6570** [comment]
Hi, 

I have restored the weights. Please check and close the issue if it is available for download.
