### ISSUE TITLE
Information on training process

### ISSUE THREAD

**Issue by Swidilator** [Blade6570/Photographic-Image-Synthesis-with-Cascaded-Refinement-Networks--Pytorch-#5]
Hi there,

I'm just wondering if it is possible to get some information on what hardware you used to train the model, as well as how long you took? I am currently writing my own version of the CRN, however I am encountering extremely long training times and massive memory requirements, and so I thought is worthwhile to find out more about other implementations and their requirments.

Kind regards

**Comment by Blade6570** [comment]
Hi,

I implemented it many days before and I exactly don't remember the time it took. However, the time for 256x256 resolution was not unreasonably high. I may have used two Nvidia GTX 1080Ti (12 GB each) at max for my training.

Thanks

**Comment by Swidilator** [comment]
Thank you for your quick response, I'll keep reviewing my code to see what's different about mine.
